# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20160618_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='like',
        ),
    ]
