# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_auto_20160618_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='card',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
