# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0007_auto_20160529_1309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default=b'', help_text=b'You can give your thoughts for the card.', verbose_name=b'Comments')),
                ('cards', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='cards.Cards')),
                ('user', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
