# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
    ]
