# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='joining_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
