# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160515_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
