# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20160515_1427'),
        ('cards', '0003_auto_20160515_1435'),
    ]

    operations = [
    ]
