# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_hero_image',
            field=models.ImageField(default='', help_text='Add', upload_to='Cards', verbose_name='Card display image'),
        ),
    ]
