# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_cards_card_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
    ]
