# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0008_cards_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='likes',
            field=models.ManyToManyField(default='', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
