# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cards_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='likes',
        ),
    ]
